Pydantic
nsidc/qgreenland pull request #228
Opened 2021-08-04 15:33 UTC by trey-stafford

2021-08-04 21:24 UTC, MattF-NSIDC requested changes

2021-08-04 21:24 UTC, MattF-NSIDC commented on qgreenland/test/util/test_misc.py
> +from qgreenland.test.fixtures import raster_layer_cfg as mock_layer_cfg  # noqa: F401
TODO: Why do we need noqa here and below? Seems like we shouldn't...

2021-08-04 21:24 UTC, MattF-NSIDC commented on qgreenland/util/luigi/tasks/fetch.py
> +    dataset_cfg = luigi.Parameter()
TODO: Should we pass dataset id and asset id instead of the actual objects? We use that pattern elsewhere so that parameters are hashable.

2021-08-06 14:46 UTC, trey-stafford commented on qgreenland/models/config/layer.py
> +    # TODO: remove.
Just one layer, Topographic map (1 to 500,000), a manual access layer from The Danish Agency for Map Supply and Efficiency.

IIRC attempts to re-project this layer yielded poor results so we stuck with the source projection.

2021-08-06 16:25 UTC, MattF-NSIDC commented on qgreenland/models/config/layer.py
> +    # TODO: remove.
Solution for this is going to be making sure the final layer has good metadata so our code can tell QGIS what projection the layer is in based on that metadata. Before, our code told QGIS everything was in the project projection except in the one case where this override was provided.

2021-08-06 16:28 UTC, MattF-NSIDC commented on qgreenland/util/config.py
> -    for index, step in enumerate(steps):
:roll_eyes: :rotating_light: :rotating_light: :rotating_light:

2021-08-06 16:28 UTC, MattF-NSIDC commented on qgreenland/util/config.py
> -        steps = before_template + dereferenced + after_template
:roll_eyes: :rotating_light: :rotating_light: :rotating_light:

2021-08-06 18:09 UTC, MattF-NSIDC approved these changes

2021-08-06 18:11 UTC, merged