Update sea ice layer
nsidc/qgreenland pull request #464
Opened 2022-02-11 15:39 UTC by hsimonoko

## Description

Update sea ice concentration layer to include 2021 data

## Checklist

If an item on this list is done _or not needed_, simply check it with `[x]`.

- [ ] Config lockfile updated (`inv config.export > qgreenland/config/cfg-lock.json`)
- [ ] Version bumped if needed (`bumpversion (major|minor|patch|prerelease|build`)
- [ ] CHANGELOG.md updated
- [ ] Documentation updated if needed
- [ ] New unit tests if needed

2022-02-15 17:30 UTC, trey-stafford requested changes
Lets remove the September 2022 layer config since that data is not available yet.

2022-02-15 17:30 UTC, trey-stafford commented on qgreenland/config/cfg-lock.json
> +            "ftp://sidads.colorado.edu/DATASETS/NOAA/G02135/north/monthly/geotiff/09_Sep/N_202209_concentration_v3.0.tif"
We can add the 'max' concentration for 2022 (March) but this layer can't be added yet. September is still a little ways off :smile: .

2022-02-15 17:30 UTC, MattF-NSIDC approved these changes

2022-02-23 18:11 UTC, trey-stafford commented on CHANGELOG.md
> +  - "Monthly Mean Concentration (25km)" updated to include 2021 data
Lets note that we are specifically updating the "Feb or March (max monthly extent)" group to include 2021 data.

2022-02-23 20:04 UTC, trey-stafford approved these changes

2022-02-23 20:04 UTC, trey-stafford commented on CHANGELOG.md
> +  - "Monthly Mean Concentration (25km) Feb or March (max monthly extent)"
One last suggestion: I'd place a `/` in between "Monthly Mean Concentration (25km)" and "Feb or March (max monthly extent)". I would also probably include the root group "Sea ice":
> "Sea ice / Monthly Mean Concentration (25km) / Feb or March (max monthly extent)" updated to include 2021 data"

Sorry to nitpick!

2022-02-23 23:48 UTC, merged